# generated by datamodel-codegen:
#   filename:  packet_definitions.json
#   timestamp: 2024-01-28T06:52:40+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class Ok(BaseModel):
    class Config:
        extra = Extra.forbid

    message: Optional[str] = None


class Deny(BaseModel):
    class Config:
        extra = Extra.forbid

    reason: Optional[str] = None


class Chat(BaseModel):
    class Config:
        extra = Extra.forbid

    sender: Optional[str] = None
    message: str


class Hello(BaseModel):
    class Config:
        extra = Extra.forbid

    username: str
    x: Optional[float] = None
    y: Optional[float] = None


class Login(BaseModel):
    class Config:
        extra = Extra.forbid

    username: str
    password: str


class Logout(BaseModel):
    class Config:
        extra = Extra.forbid

    username: str


class Register(BaseModel):
    class Config:
        extra = Extra.forbid

    username: str
    password: str


class Move(BaseModel):
    class Config:
        extra = Extra.forbid

    username: str
    x: Optional[float] = None
    y: Optional[float] = None


class Model(BaseModel):
    class Config:
        extra = Extra.forbid

    Ok: Optional[Ok] = None
    Deny: Optional[Deny] = None
    Chat: Optional[Chat] = None
    Hello: Optional[Hello] = None
    Login: Optional[Login] = None
    Logout: Optional[Logout] = None
    Register: Optional[Register] = None
    Move: Optional[Move] = None
